# Generated by Django 2.2.4 on 2020-10-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_name', models.CharField(max_length=255)),
                ('oscillator1', models.CharField(max_length=25)),
                ('octave1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attackGain1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attackDur1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('decayDur1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sustainGain1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sustainDur1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('oscillator2', models.CharField(max_length=25)),
                ('octave2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attackGain2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attackDur2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('decayDur2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sustainGain2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sustainDur2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_by', models.ManyToManyField(related_name='saved_patches', to='synth_app.User')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='synth_app.User')),
            ],
        ),
    ]
